spring:
  application:
    name: xc-govern-center
eureka:
  client:
    service-url:
      #defaultZone: ${EUREKA_NAME:http://${eureka.instance}:${server.port}/eureka/}
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false  #是否注册到eureka中，如果是只有一个eureka没必要再注册上去了
    fetch-registry: false    #从eureka里获取注册列表
  server:
    enable-self-preservation: false
    delta-retention-timer-interval-in-ms: 60000
  instance: ${INSTANCE:localhost}
server:
  port: ${PORT:8761}


#spring:
#  application:
#    name: eureka
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#
#server:
#  port: 8761


