server:
  port: 31002
spring:
  application:
    name: cms_client
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017
      database: xc_cms
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
    connection-timeout: 15000
        
        
xuecheng:
  mq:
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1 #此routingKey为门户站点ID
    
    

  
